In [116]:
import pandas as pd
import numpy as np

In [117]:
df = pd.read_csv("UNSW_2018_IoT_Botnet_Dataset_1.csv",delimiter=',', quotechar='"',index_col=0,low_memory=False)

In [118]:
df.head()

B  C    D                E      F               G      H   I    J  \
A                                                                               
2  1526344223  e  tcp    192.168.100.7    139   192.168.100.4  36390  10  680   
3  1526344227  e  udp  192.168.100.149  51838  27.124.125.250    123   2  180   
4  1526344228  e  arp    192.168.100.4    NaN   192.168.100.7    NaN  10  510   
5  1526344303  e  udp   192.168.100.27  58999   192.168.100.1     53   4  630   
6  1526344303  e  arp    192.168.100.1    NaN  192.168.100.27    NaN   2  120   

     K  ...  Z  AA   AB   AC           AD        AE        AF  label  Normal  \
A       ...                                                                    
2  CON  ...  5   5  350  330     0.006190  0.002751  0.002751      0  Normal   
3  CON  ...  1   1   90   90    20.590960  0.000000  0.000000      0  Normal   
4  CON  ...  5   5  210  300     0.006189  0.002751  0.002751      0  Normal   
5  CON  ...  2   2  174  456     0.005264  0.001755  0.001755      0  Normal   
6  CON  ...  1   1   60   60  2724.795654  0.000000  0.000000      0  Normal   

   Normal.1  
A            
2    Normal  
3    Normal  
4    Normal  
5    Normal  
6    Normal  

[5 rows x 34 columns]

In [119]:
df = df[["J","N","O","P","S","T","U","AD","AE","label"]]

In [120]:
df.head()

J            N         O         P         S         T         U  \
A                                                                       
2  680  1453.945923  0.000028  0.000008  0.000138  0.000022  0.000042   
3  180     0.048565  0.048565  0.000000  0.048565  0.048565  0.048565   
4  510  1454.080322  0.000238  0.000022  0.001189  0.000199  0.000261   
5  630   569.933960  0.098505  0.080150  0.197011  0.018356  0.178655   
6  120     0.000367  0.000367  0.000000  0.000367  0.000367  0.000367   

            AD        AE  label  
A                                
2     0.006190  0.002751      0  
3    20.590960  0.000000      0  
4     0.006189  0.002751      0  
5     0.005264  0.001755      0  
6  2724.795654  0.000000      0

In [121]:
df[df.label == 0].head()

J            N         O         P         S         T         U  \
A                                                                       
2  680  1453.945923  0.000028  0.000008  0.000138  0.000022  0.000042   
3  180     0.048565  0.048565  0.000000  0.048565  0.048565  0.048565   
4  510  1454.080322  0.000238  0.000022  0.001189  0.000199  0.000261   
5  630   569.933960  0.098505  0.080150  0.197011  0.018356  0.178655   
6  120     0.000367  0.000367  0.000000  0.000367  0.000367  0.000367   

            AD        AE  label  
A                                
2     0.006190  0.002751      0  
3    20.590960  0.000000      0  
4     0.006189  0.002751      0  
5     0.005264  0.001755      0  
6  2724.795654  0.000000      0

In [122]:
df[df.label == 1].head()

J         N         O    P         S         T         U           AD  \
A                                                                             
13  120  0.000108  0.000108  0.0  0.000108  0.000108  0.000108  9259.258789   
14  120  0.000107  0.000107  0.0  0.000107  0.000107  0.000107  9345.793945   
15  180  0.000220  0.000220  0.0  0.000220  0.000220  0.000220  9090.909180   
16  120  0.000131  0.000131  0.0  0.000131  0.000131  0.000131  7633.588379   
17  120  0.000130  0.000130  0.0  0.000130  0.000130  0.000130  7692.307617   

            AE  label  
A                      
13     0.00000      1  
14     0.00000      1  
15  4545.45459      1  
16     0.00000      1  
17     0.00000      1

In [123]:
df.dtypes

J          int64
N        float64
O        float64
P        float64
S        float64
T        float64
U        float64
AD       float64
AE       float64
label      int64
dtype: object

In [124]:
df.head()

J            N         O         P         S         T         U  \
A                                                                       
2  680  1453.945923  0.000028  0.000008  0.000138  0.000022  0.000042   
3  180     0.048565  0.048565  0.000000  0.048565  0.048565  0.048565   
4  510  1454.080322  0.000238  0.000022  0.001189  0.000199  0.000261   
5  630   569.933960  0.098505  0.080150  0.197011  0.018356  0.178655   
6  120     0.000367  0.000367  0.000000  0.000367  0.000367  0.000367   

            AD        AE  label  
A                                
2     0.006190  0.002751      0  
3    20.590960  0.000000      0  
4     0.006189  0.002751      0  
5     0.005264  0.001755      0  
6  2724.795654  0.000000      0

In [125]:
from sklearn.model_selection import train_test_split

In [126]:
x = df.drop('label', axis='columns')

In [127]:
y = df.label

In [128]:
X_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [129]:
len(X_train)

799999

In [130]:
len(x_test)

200000

In [131]:
from sklearn.preprocessing import StandardScaler

In [132]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [133]:
X_train = scaler.transform(X_train)
x_test = scaler.transform(x_test)

In [77]:
from sklearn.neighbors import KNeighborsClassifier

In [78]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [79]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [80]:
knn.score(x_test,y_test)

0.99938

In [81]:
from sklearn.metrics import confusion_matrix
y_pred = knn.predict(x_test)
cm = confusion_matrix(y_test,y_pred)

In [82]:
cm

array([[   291,    116],
       [     8, 199585]], dtype=int64)

In [103]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     70147
           1       0.95      0.96      0.95     17862

    accuracy                           0.98     88009
   macro avg       0.97      0.97      0.97     88009
weighted avg       0.98      0.98      0.98     88009



In [83]:
#Random Forest Classification

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [85]:
clf = RandomForestClassifier(max_depth=2, random_state=0)

In [86]:
clf.fit(X_train,y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [87]:
clf.score(x_test,y_test)

0.998225

In [88]:
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(x_test)
cm = confusion_matrix(y_test,y_pred)

In [89]:
cm

array([[    52,    355],
       [     0, 199593]], dtype=int64)

In [110]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97     70147
           1       0.98      0.75      0.85     17862

    accuracy                           0.95     88009
   macro avg       0.96      0.88      0.91     88009
weighted avg       0.95      0.95      0.94     88009



In [90]:
#Decision tree classification

In [96]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=0, max_depth=2)

In [97]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2, random_state=0)

In [98]:
dt.score(x_test,y_test)

0.998225

In [102]:
from sklearn.metrics import confusion_matrix
y_pred = dt.predict(x_test)
cm = confusion_matrix(y_test,y_pred)

In [103]:
cm

array([[    52,    355],
       [     0, 199593]], dtype=int64)

In [104]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.13      0.23       407
           1       1.00      1.00      1.00    199593

    accuracy                           1.00    200000
   macro avg       1.00      0.56      0.61    200000
weighted avg       1.00      1.00      1.00    200000



In [105]:
#Gaussian Naive Bayes

In [106]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [107]:
gnb.fit(X_train,y_train)

GaussianNB()

In [108]:
gnb.score(x_test,y_test)

0.989865

In [109]:
from sklearn.metrics import confusion_matrix
y_pred = gnb.predict(x_test)
cm = confusion_matrix(y_test,y_pred)

In [110]:
cm

array([[    96,    311],
       [  1716, 197877]], dtype=int64)

In [111]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.05      0.24      0.09       407
           1       1.00      0.99      0.99    199593

    accuracy                           0.99    200000
   macro avg       0.53      0.61      0.54    200000
weighted avg       1.00      0.99      0.99    200000



In [112]:
#ANN classification

In [134]:
from sklearn.neural_network import MLPClassifier

In [135]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

In [136]:
clf.fit(X_train,y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [137]:
clf.score(x_test,y_test)

0.99822

In [138]:
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(x_test)
cm = confusion_matrix(y_test,y_pred)

In [139]:
cm

array([[    51,    356],
       [     0, 199593]], dtype=int64)

In [140]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.13      0.22       407
           1       1.00      1.00      1.00    199593

    accuracy                           1.00    200000
   macro avg       1.00      0.56      0.61    200000
weighted avg       1.00      1.00      1.00    200000

